services:
  - type: web
    name: eki-laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: crossover.proxy.rlwy.net
      - key: DB_PORT
        value: 36170
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: WEcCBhysnTpwaIGbApKfLUddrUVSSCLP
    healthCheckPath: /
    autoDeploy: true
